## Barcelona Beer Challenge

### Saturdays.AI first challenge competition

I wrote this notebook as part of the submission for this Kaggle competition : https://www.kaggle.com/c/barcelona-beer-challenge/overview

When working on it I was very new to Machine Learning and have simply tried out the Support Vector Machine on this challenge. 

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv("beer_train.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24066 entries, 0 to 24065
Data columns (total 17 columns):
Id               24066 non-null int64
Size(L)          24066 non-null float64
OG               24066 non-null float64
FG               24066 non-null float64
ABV              24066 non-null float64
IBU              24066 non-null float64
Color            24066 non-null float64
BoilSize         24066 non-null float64
BoilTime         24066 non-null int64
BoilGravity      23130 non-null float64
Efficiency       24066 non-null float64
MashThickness    14200 non-null float64
SugarScale       24066 non-null object
BrewMethod       24066 non-null object
PitchRate        10932 non-null float64
PrimaryTemp      16578 non-null float64
Style            24066 non-null object
dtypes: float64(12), int64(2), object(3)
memory usage: 3.1+ MB


In [4]:
df.describe()

Id       Size(L)            OG            FG           ABV  \
count  24066.000000  24066.000000  24066.000000  24066.000000  24066.000000   
mean   12032.500000     45.702692      1.367517      1.065335      6.005748   
std     6947.400125    186.624603      2.039252      0.364336      1.402203   
min        0.000000      1.000000      1.000000      0.598715      0.000000   
25%     6016.250000     18.930000      1.051000      1.011000      5.180000   
50%    12032.500000     20.820000      1.058000      1.013000      5.880000   
75%    18048.750000     24.000000      1.066000      1.016000      6.680000   
max    24065.000000   6102.080000     23.445000      7.745770     49.960000   

                IBU         Color      BoilSize      BoilTime   BoilGravity  \
count  24066.000000  24066.000000  24066.000000  24066.000000  23130.000000   
mean      52.305999     10.171609     51.652292     63.776573      1.321495   
std       43.487405      8.726041    199.448712     12.091712      1.782509   
min        0.000000      0.000000      1.000000      0.000000      0.000000   
25%       28.522500      5.250000     21.000000     60.000000      1.040000   
50%       43.310000      7.280000     28.000000     60.000000      1.047000   
75%       65.780000     11.140000     30.000000     60.000000      1.057000   
max     1605.830000    108.650000   6454.130000    240.000000     38.300000   

         Efficiency  MashThickness     PitchRate   PrimaryTemp  
count  24066.000000   14200.000000  10932.000000  16578.000000  
mean      66.040676       2.143376      0.677991     19.765436  
std       14.131211       1.752144      0.321470      3.645587  
min        0.000000       0.000000      0.000000    -17.780000  
25%       65.000000       1.500000      0.350000     18.330000  
50%       70.000000       1.500000      0.750000     20.000000  
75%       75.000000       3.000000      0.750000     21.000000  
max      100.000000      54.000000      2.000000     85.000000

In [5]:
df.isnull().sum()

Id                   0
Size(L)              0
OG                   0
FG                   0
ABV                  0
IBU                  0
Color                0
BoilSize             0
BoilTime             0
BoilGravity        936
Efficiency           0
MashThickness     9866
SugarScale           0
BrewMethod           0
PitchRate        13134
PrimaryTemp       7488
Style                0
dtype: int64

In [6]:
df.head()

Id  Size(L)     OG     FG   ABV     IBU  Color  BoilSize  BoilTime  \
0   0    22.71  1.071  1.021  6.51   81.14   6.43     28.39        90   
1   1     7.57  1.062  1.016  6.14  138.44  15.28      7.57        60   
2   2    12.00  1.051  1.012  5.17   27.57  14.54     14.00        60   
3   3    15.00  1.051  1.013  5.01   38.53  26.73     19.00        90   
4   4    21.77  1.061  1.013  6.25   43.20   4.08     23.66        15   

   BoilGravity  Efficiency  MashThickness        SugarScale BrewMethod  \
0        1.057        78.0            1.2  Specific Gravity  All Grain   
1        1.062        35.0            NaN  Specific Gravity    extract   
2        1.041        65.0            NaN  Specific Gravity       BIAB   
3        1.040        65.0            3.0  Specific Gravity  All Grain   
4        1.045        35.0            NaN  Specific Gravity    extract   

   PitchRate  PrimaryTemp           Style  
0        NaN         20.0    American IPA  
1       0.50         20.0    American IPA  
2       0.35         20.0   Irish Red Ale  
3        NaN          NaN  American Stout  
4       0.75         20.0    American IPA

In [7]:
list(df.columns.values) 

['Id',
 'Size(L)',
 'OG',
 'FG',
 'ABV',
 'IBU',
 'Color',
 'BoilSize',
 'BoilTime',
 'BoilGravity',
 'Efficiency',
 'MashThickness',
 'SugarScale',
 'BrewMethod',
 'PitchRate',
 'PrimaryTemp',
 'Style']

In [8]:
df["SugarScale"].value_counts()

Specific Gravity    23506
Plato                 560
Name: SugarScale, dtype: int64

In [9]:
df["Style"].value_counts()

American IPA            8358
American Pale Ale       5307
Saison                  1832
American Light Lager    1594
American Amber Ale      1427
Blonde Ale              1227
Imperial IPA            1034
American Stout           888
Irish Red Ale            843
American Brown Ale       806
Witbier                  750
Name: Style, dtype: int64

In [10]:
df = df.drop(["PitchRate"], axis = 1)



In [11]:
df.head()

Id  Size(L)     OG     FG   ABV     IBU  Color  BoilSize  BoilTime  \
0   0    22.71  1.071  1.021  6.51   81.14   6.43     28.39        90   
1   1     7.57  1.062  1.016  6.14  138.44  15.28      7.57        60   
2   2    12.00  1.051  1.012  5.17   27.57  14.54     14.00        60   
3   3    15.00  1.051  1.013  5.01   38.53  26.73     19.00        90   
4   4    21.77  1.061  1.013  6.25   43.20   4.08     23.66        15   

   BoilGravity  Efficiency  MashThickness        SugarScale BrewMethod  \
0        1.057        78.0            1.2  Specific Gravity  All Grain   
1        1.062        35.0            NaN  Specific Gravity    extract   
2        1.041        65.0            NaN  Specific Gravity       BIAB   
3        1.040        65.0            3.0  Specific Gravity  All Grain   
4        1.045        35.0            NaN  Specific Gravity    extract   

   PrimaryTemp           Style  
0         20.0    American IPA  
1         20.0    American IPA  
2         20.0   Irish Red Ale  
3          NaN  American Stout  
4         20.0    American IPA

In [12]:
df['SugarScale'].replace(['Specific Gravity','Plato'],[0,1],inplace=True)


In [13]:
df["SugarScale"].value_counts()

0    23506
1      560
Name: SugarScale, dtype: int64

In [14]:
df["BrewMethod"].value_counts()

All Grain       16042
BIAB             3960
extract          2948
Partial Mash     1116
Name: BrewMethod, dtype: int64

In [15]:
df['BrewMethod'].replace(['All Grain','BIAB',"extract","Partial Mash",],[0,1,2,3],inplace=True)


In [16]:
df["BrewMethod"].value_counts()

0    16042
1     3960
2     2948
3     1116
Name: BrewMethod, dtype: int64

In [17]:
df["Style"].unique()

array(['American IPA', 'Irish Red Ale', 'American Stout',
       'American Amber Ale', 'Saison', 'American Pale Ale',
       'American Light Lager', 'Imperial IPA', 'American Brown Ale',
       'Witbier', 'Blonde Ale'], dtype=object)

In [18]:
df['Style'].replace(['American IPA', 'Irish Red Ale', 'American Stout','American Amber Ale', 'Saison', 'American Pale Ale','American Light Lager', 'Imperial IPA', 'American Brown Ale','Witbier', 'Blonde Ale'],[0,1,2,3,4,5,6,7,8,9,10],inplace=True)



In [19]:
df["Style"].value_counts()

0     8358
5     5307
4     1832
6     1594
3     1427
10    1227
7     1034
2      888
1      843
8      806
9      750
Name: Style, dtype: int64

In [20]:
df["Style"].astype("int")

0        0
1        0
2        1
3        2
4        0
        ..
24061    0
24062    0
24063    1
24064    3
24065    5
Name: Style, Length: 24066, dtype: int64

In [21]:
#import xgboost as xgb
from sklearn.model_selection import train_test_split
from catboost import CatBoostRegressor
from catboost import CatBoostClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import AdaBoostRegressor
#import lightgbm as lgb
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [22]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [23]:
df_it = df.iloc[:,0:16]
imp = IterativeImputer(max_iter=10, verbose=0)
imp.fit(df_it)
imputed_df = imp.transform(df_it)
imputed_df = pd.DataFrame(imputed_df, columns=df_it.columns)


In [24]:
df_it.head()

Id  Size(L)     OG     FG   ABV     IBU  Color  BoilSize  BoilTime  \
0   0    22.71  1.071  1.021  6.51   81.14   6.43     28.39        90   
1   1     7.57  1.062  1.016  6.14  138.44  15.28      7.57        60   
2   2    12.00  1.051  1.012  5.17   27.57  14.54     14.00        60   
3   3    15.00  1.051  1.013  5.01   38.53  26.73     19.00        90   
4   4    21.77  1.061  1.013  6.25   43.20   4.08     23.66        15   

   BoilGravity  Efficiency  MashThickness  SugarScale  BrewMethod  \
0        1.057        78.0            1.2           0           0   
1        1.062        35.0            NaN           0           2   
2        1.041        65.0            NaN           0           1   
3        1.040        65.0            3.0           0           0   
4        1.045        35.0            NaN           0           2   

   PrimaryTemp  Style  
0         20.0      0  
1         20.0      0  
2         20.0      1  
3          NaN      2  
4         20.0      0

In [25]:
imputed_df.head()

Id  Size(L)     OG     FG   ABV     IBU  Color  BoilSize  BoilTime  \
0  0.0    22.71  1.071  1.021  6.51   81.14   6.43     28.39      90.0   
1  1.0     7.57  1.062  1.016  6.14  138.44  15.28      7.57      60.0   
2  2.0    12.00  1.051  1.012  5.17   27.57  14.54     14.00      60.0   
3  3.0    15.00  1.051  1.013  5.01   38.53  26.73     19.00      90.0   
4  4.0    21.77  1.061  1.013  6.25   43.20   4.08     23.66      15.0   

   BoilGravity  Efficiency  MashThickness  SugarScale  BrewMethod  \
0        1.057        78.0       1.200000         0.0         0.0   
1        1.062        35.0       1.908379         0.0         2.0   
2        1.041        65.0       2.172369         0.0         1.0   
3        1.040        65.0       3.000000         0.0         0.0   
4        1.045        35.0       1.999421         0.0         2.0   

   PrimaryTemp  Style  
0    20.000000    0.0  
1    20.000000    0.0  
2    20.000000    1.0  
3    19.908087    2.0  
4    20.000000    0.0

In [26]:
df = imputed_df

In [27]:
df.head()

Id  Size(L)     OG     FG   ABV     IBU  Color  BoilSize  BoilTime  \
0  0.0    22.71  1.071  1.021  6.51   81.14   6.43     28.39      90.0   
1  1.0     7.57  1.062  1.016  6.14  138.44  15.28      7.57      60.0   
2  2.0    12.00  1.051  1.012  5.17   27.57  14.54     14.00      60.0   
3  3.0    15.00  1.051  1.013  5.01   38.53  26.73     19.00      90.0   
4  4.0    21.77  1.061  1.013  6.25   43.20   4.08     23.66      15.0   

   BoilGravity  Efficiency  MashThickness  SugarScale  BrewMethod  \
0        1.057        78.0       1.200000         0.0         0.0   
1        1.062        35.0       1.908379         0.0         2.0   
2        1.041        65.0       2.172369         0.0         1.0   
3        1.040        65.0       3.000000         0.0         0.0   
4        1.045        35.0       1.999421         0.0         2.0   

   PrimaryTemp  Style  
0    20.000000    0.0  
1    20.000000    0.0  
2    20.000000    1.0  
3    19.908087    2.0  
4    20.000000    0.0

In [28]:
features = df.columns.to_list()[:15]
x = df.loc[:, features].values
x_std = StandardScaler().fit_transform(x) # normalizing the features

In [29]:
round(np.mean(x_std),1),np.std(x_std)

(0.0, 1.0)

In [30]:
feat_cols = ['feature'+str(i) for i in range(x_std.shape[1])]
normalised_dataset = pd.DataFrame(x_std,columns=feat_cols)
normalised_dataset.head()

feature0  feature1  feature2  feature3  feature4  feature5  feature6  \
0 -1.731979 -0.123205 -0.145408 -0.121689  0.359621  0.663056 -0.428795   
1 -1.731835 -0.204333 -0.149821 -0.135413  0.095745  1.980707  0.585431   
2 -1.731691 -0.180595 -0.155215 -0.146392 -0.596038 -0.568820  0.500626   
3 -1.731547 -0.164519 -0.155215 -0.143647 -0.710146 -0.316788  1.897623   
4 -1.731403 -0.128242 -0.150312 -0.143647  0.174195 -0.209398 -0.698110   

   feature7  feature8  feature9  feature10  feature11  feature12  feature13  \
0 -0.116635  2.168756 -0.145984   0.846323  -0.694813  -0.154349  -0.624905   
1 -0.221025 -0.312334 -0.143140  -2.196650  -0.169851  -0.154349   1.653035   
2 -0.188786 -0.312334 -0.155086  -0.073645   0.025786  -0.154349   0.514065   
3 -0.163716  2.168756 -0.155654  -0.073645   0.639122  -0.154349  -0.624905   
4 -0.140351 -4.033969 -0.152810  -2.196650  -0.102382  -0.154349   1.653035   

   feature14  
0   0.076538  
1   0.076538  
2   0.076538  
3   0.046185  
4   0.076538

In [31]:
X = normalised_dataset
y = df['Style']

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [33]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [34]:
y_pred = svclassifier.predict(X_test)

In [35]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[1318    3   27    6   55  200    5   13    9    6   10]
 [  18   59    0   58    3   25    0    0   16    0    1]
 [   5    0  167    0    1    2    0    1   15    0    0]
 [  78   30    3   86    6   63    5    0   13    1    1]
 [  58    3    3    9  146  104    1    1    6   10   10]
 [ 246    4    3    9   28  745    4    0    2   18   20]
 [  61    9   21    6   27   73   17    5    8   33   34]
 [ 162    1    4    0    6    0    0   42    1    0    0]
 [   9   15   18    6    1    2    0    3  102    0    0]
 [   5    0    1    0   34   22    3    0    1   54   40]
 [  23    3    0    2   19  138    4    0    0   14   46]]
              precision    recall  f1-score   support

         0.0       0.66      0.80      0.73      1652
         1.0       0.46      0.33      0.38       180
         2.0       0.68      0.87      0.76       191
         3.0       0.47      0.30      0.37       286
         4.0       0.45      0.42      0.43       351
         5.0       0.54      0.69   

In [36]:
df_test = pd.read_csv("beer_test.csv")

In [37]:
df_test.isnull().sum()

Id                  0
Size(L)             0
OG                  0
FG                  0
ABV                 0
IBU                 0
Color               0
BoilSize            0
BoilTime            0
BoilGravity       332
Efficiency          0
MashThickness    4166
SugarScale          0
BrewMethod          0
PitchRate        5651
PrimaryTemp      3171
dtype: int64

In [38]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10314 entries, 0 to 10313
Data columns (total 16 columns):
Id               10314 non-null int64
Size(L)          10314 non-null float64
OG               10314 non-null float64
FG               10314 non-null float64
ABV              10314 non-null float64
IBU              10314 non-null float64
Color            10314 non-null float64
BoilSize         10314 non-null float64
BoilTime         10314 non-null int64
BoilGravity      9982 non-null float64
Efficiency       10314 non-null float64
MashThickness    6148 non-null float64
SugarScale       10314 non-null object
BrewMethod       10314 non-null object
PitchRate        4663 non-null float64
PrimaryTemp      7143 non-null float64
dtypes: float64(12), int64(2), object(2)
memory usage: 1.3+ MB


In [39]:
df_test = df_test.drop(["PitchRate"], axis = 1)

In [40]:
df_test.head()

Id  Size(L)       OG       FG   ABV    IBU  Color  BoilSize  BoilTime  \
0   0    20.82  15.6465  4.23184  6.21  55.13   8.20     28.01        90   
1   1    20.82   1.0570  1.01300  5.71  51.99   6.35     28.39        60   
2   2    22.71   1.0580  1.01400  5.67  54.77  24.75     28.39        60   
3   3    10.00   1.0520  1.01000  5.51  93.58   5.46     28.50        60   
4   4    20.00  12.0478  1.32023  5.70  33.72   3.58     30.00        60   

   BoilGravity  Efficiency  MashThickness        SugarScale BrewMethod  \
0       11.800        70.0            1.3             Plato  All Grain   
1        1.042        70.0            NaN  Specific Gravity  All Grain   
2        1.046        75.0            1.5  Specific Gravity  All Grain   
3        1.018        75.0            1.5  Specific Gravity  All Grain   
4        8.100        75.0            3.0             Plato  All Grain   

   PrimaryTemp  
0        25.56  
1          NaN  
2        20.00  
3        17.00  
4        27.00

In [41]:
df_test['SugarScale'].replace(['Specific Gravity','Plato'],[0,1],inplace=True)


In [42]:
df_test['BrewMethod'].replace(['All Grain','BIAB',"extract","Partial Mash",],[0,1,2,3],inplace=True)


In [43]:
df_test.head()

Id  Size(L)       OG       FG   ABV    IBU  Color  BoilSize  BoilTime  \
0   0    20.82  15.6465  4.23184  6.21  55.13   8.20     28.01        90   
1   1    20.82   1.0570  1.01300  5.71  51.99   6.35     28.39        60   
2   2    22.71   1.0580  1.01400  5.67  54.77  24.75     28.39        60   
3   3    10.00   1.0520  1.01000  5.51  93.58   5.46     28.50        60   
4   4    20.00  12.0478  1.32023  5.70  33.72   3.58     30.00        60   

   BoilGravity  Efficiency  MashThickness  SugarScale  BrewMethod  PrimaryTemp  
0       11.800        70.0            1.3           1           0        25.56  
1        1.042        70.0            NaN           0           0          NaN  
2        1.046        75.0            1.5           0           0        20.00  
3        1.018        75.0            1.5           0           0        17.00  
4        8.100        75.0            3.0           1           0        27.00

In [44]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [45]:
df_test_it = df_test.iloc[:,0:16]
imp = IterativeImputer(max_iter=10, verbose=0)
imp.fit(df_test_it)
imputed_test_df = imp.transform(df_test_it)
imputed_test_df = pd.DataFrame(imputed_test_df, columns=df_test_it.columns)



In [46]:
imputed_test_df.head()

Id  Size(L)       OG       FG   ABV    IBU  Color  BoilSize  BoilTime  \
0  0.0    20.82  15.6465  4.23184  6.21  55.13   8.20     28.01      90.0   
1  1.0    20.82   1.0570  1.01300  5.71  51.99   6.35     28.39      60.0   
2  2.0    22.71   1.0580  1.01400  5.67  54.77  24.75     28.39      60.0   
3  3.0    10.00   1.0520  1.01000  5.51  93.58   5.46     28.50      60.0   
4  4.0    20.00  12.0478  1.32023  5.70  33.72   3.58     30.00      60.0   

   BoilGravity  Efficiency  MashThickness  SugarScale  BrewMethod  PrimaryTemp  
0       11.800        70.0       1.300000         1.0         0.0    25.560000  
1        1.042        70.0       2.083965         0.0         0.0    19.690353  
2        1.046        75.0       1.500000         0.0         0.0    20.000000  
3        1.018        75.0       1.500000         0.0         0.0    17.000000  
4        8.100        75.0       3.000000         1.0         0.0    27.000000

In [47]:
df_test = imputed_test_df

In [48]:
df_test.head()

Id  Size(L)       OG       FG   ABV    IBU  Color  BoilSize  BoilTime  \
0  0.0    20.82  15.6465  4.23184  6.21  55.13   8.20     28.01      90.0   
1  1.0    20.82   1.0570  1.01300  5.71  51.99   6.35     28.39      60.0   
2  2.0    22.71   1.0580  1.01400  5.67  54.77  24.75     28.39      60.0   
3  3.0    10.00   1.0520  1.01000  5.51  93.58   5.46     28.50      60.0   
4  4.0    20.00  12.0478  1.32023  5.70  33.72   3.58     30.00      60.0   

   BoilGravity  Efficiency  MashThickness  SugarScale  BrewMethod  PrimaryTemp  
0       11.800        70.0       1.300000         1.0         0.0    25.560000  
1        1.042        70.0       2.083965         0.0         0.0    19.690353  
2        1.046        75.0       1.500000         0.0         0.0    20.000000  
3        1.018        75.0       1.500000         0.0         0.0    17.000000  
4        8.100        75.0       3.000000         1.0         0.0    27.000000

In [49]:
features = df_test.columns.to_list()[:16]
x = df_test.loc[:, features].values
x_std = StandardScaler().fit_transform(x) # normalizing the features

In [50]:
round(np.mean(x_std),1),np.std(x_std)

(-0.0, 0.9999999999999999)

In [51]:
feat_cols = ['feature'+str(i) for i in range(x_std.shape[1])]
normalised_test_dataset = pd.DataFrame(x_std,columns=feat_cols)
normalised_test_dataset.head()

feature0  feature1  feature2  feature3  feature4  feature5  feature6  \
0 -1.731883 -0.130471  7.172704  8.524501  0.122622  0.065400 -0.227860   
1 -1.731547 -0.130471 -0.152580 -0.140663 -0.203986 -0.001780 -0.443443   
2 -1.731211 -0.119713 -0.152078 -0.137971 -0.230115  0.057698  1.700731   
3 -1.730875 -0.192061 -0.155090 -0.148739 -0.334630  0.888040 -0.547155   
4 -1.730539 -0.135139  5.365822  0.686404 -0.210519 -0.392668 -0.766234   

   feature7  feature8  feature9  feature10  feature11  feature12  feature13  \
0 -0.114844  2.146452  6.056470   0.279565  -0.642821   6.492674  -0.626298   
1 -0.112792 -0.295546 -0.153840   0.279565   0.032089  -0.154020  -0.626298   
2 -0.112792 -0.295546 -0.151531   0.632928  -0.470642  -0.154020  -0.626298   
3 -0.112198 -0.295546 -0.167695   0.632928  -0.470642  -0.154020  -0.626298   
4 -0.104097 -0.295546  3.920558   0.632928   0.820697   6.492674  -0.626298   

   feature14  
0   2.073526  
1  -0.015434  
2   0.094767  
3  -0.972909  
4   2.586010

In [52]:
X_test = normalised_test_dataset
y_pred = svclassifier.predict(X_test)

In [53]:
print(y_pred)

[0. 0. 8. ... 0. 0. 0.]


In [54]:
y_pred.shape

(10314,)

In [55]:
normalised_test_dataset['Style'] = y_pred
print(normalised_test_dataset)

       feature0  feature1  feature2  feature3  feature4  feature5  feature6  \
0     -1.731883 -0.130471  7.172704  8.524501  0.122622  0.065400 -0.227860   
1     -1.731547 -0.130471 -0.152580 -0.140663 -0.203986 -0.001780 -0.443443   
2     -1.731211 -0.119713 -0.152078 -0.137971 -0.230115  0.057698  1.700731   
3     -1.730875 -0.192061 -0.155090 -0.148739 -0.334630  0.888040 -0.547155   
4     -1.730539 -0.135139  5.365822  0.686404 -0.210519 -0.392668 -0.766234   
...         ...       ...       ...       ...       ...       ...       ...   
10309  1.730539 -0.033532 -0.149065 -0.127203  0.018108 -0.430537 -0.540163   
10310  1.730875 -0.141229 -0.152078 -0.143355  0.037704 -0.291469 -0.159107   
10311  1.731211 -0.112370 -0.151073 -0.143355  0.122622  0.950514  0.282547   
10312  1.731547 -0.135139 -0.140529 -0.108359  1.246157  2.123818 -0.136966   
10313  1.731883 -0.135879 -0.146554 -0.135279  0.651729  0.087865  0.937452   

       feature7  feature8  feature9  feature10  fea

In [56]:
normalised_test_dataset['Style'].replace([0,1,2,3,4,5,6,7,8,9,10],['American IPA', 'Irish Red Ale', 'American Stout','American Amber Ale', 'Saison', 'American Pale Ale','American Light Lager', 'Imperial IPA', 'American Brown Ale','Witbier', 'Blonde Ale'],inplace=True)


In [57]:
normalised_test_dataset.head()

feature0  feature1  feature2  feature3  feature4  feature5  feature6  \
0 -1.731883 -0.130471  7.172704  8.524501  0.122622  0.065400 -0.227860   
1 -1.731547 -0.130471 -0.152580 -0.140663 -0.203986 -0.001780 -0.443443   
2 -1.731211 -0.119713 -0.152078 -0.137971 -0.230115  0.057698  1.700731   
3 -1.730875 -0.192061 -0.155090 -0.148739 -0.334630  0.888040 -0.547155   
4 -1.730539 -0.135139  5.365822  0.686404 -0.210519 -0.392668 -0.766234   

   feature7  feature8  feature9  feature10  feature11  feature12  feature13  \
0 -0.114844  2.146452  6.056470   0.279565  -0.642821   6.492674  -0.626298   
1 -0.112792 -0.295546 -0.153840   0.279565   0.032089  -0.154020  -0.626298   
2 -0.112792 -0.295546 -0.151531   0.632928  -0.470642  -0.154020  -0.626298   
3 -0.112198 -0.295546 -0.167695   0.632928  -0.470642  -0.154020  -0.626298   
4 -0.104097 -0.295546  3.920558   0.632928   0.820697   6.492674  -0.626298   

   feature14               Style  
0   2.073526        American IPA  
1  -0.015434        American IPA  
2   0.094767  American Brown Ale  
3  -0.972909        American IPA  
4   2.586010              Saison

In [58]:
#submission = df_test["Id"]
#normalised_test_dataset["Style"]


In [59]:
normalised_test_dataset.head()

feature0  feature1  feature2  feature3  feature4  feature5  feature6  \
0 -1.731883 -0.130471  7.172704  8.524501  0.122622  0.065400 -0.227860   
1 -1.731547 -0.130471 -0.152580 -0.140663 -0.203986 -0.001780 -0.443443   
2 -1.731211 -0.119713 -0.152078 -0.137971 -0.230115  0.057698  1.700731   
3 -1.730875 -0.192061 -0.155090 -0.148739 -0.334630  0.888040 -0.547155   
4 -1.730539 -0.135139  5.365822  0.686404 -0.210519 -0.392668 -0.766234   

   feature7  feature8  feature9  feature10  feature11  feature12  feature13  \
0 -0.114844  2.146452  6.056470   0.279565  -0.642821   6.492674  -0.626298   
1 -0.112792 -0.295546 -0.153840   0.279565   0.032089  -0.154020  -0.626298   
2 -0.112792 -0.295546 -0.151531   0.632928  -0.470642  -0.154020  -0.626298   
3 -0.112198 -0.295546 -0.167695   0.632928  -0.470642  -0.154020  -0.626298   
4 -0.104097 -0.295546  3.920558   0.632928   0.820697   6.492674  -0.626298   

   feature14               Style  
0   2.073526        American IPA  
1  -0.015434        American IPA  
2   0.094767  American Brown Ale  
3  -0.972909        American IPA  
4   2.586010              Saison

In [63]:

submission = df_test[["Id"]].copy()

In [64]:
submission

Id
0          0.0
1          1.0
2          2.0
3          3.0
4          4.0
...        ...
10309  10309.0
10310  10310.0
10311  10311.0
10312  10312.0
10313  10313.0

[10314 rows x 1 columns]

In [65]:
sub_style = normalised_test_dataset[["Style"]].copy()

In [66]:
sub_style

Style
0            American IPA
1            American IPA
2      American Brown Ale
3            American IPA
4                  Saison
...                   ...
10309              Saison
10310        American IPA
10311        American IPA
10312        American IPA
10313        American IPA

[10314 rows x 1 columns]

In [67]:
submission1 = pd.concat([submission, sub_style], axis=1)

In [68]:
submission1

Id               Style
0          0.0        American IPA
1          1.0        American IPA
2          2.0  American Brown Ale
3          3.0        American IPA
4          4.0              Saison
...        ...                 ...
10309  10309.0              Saison
10310  10310.0        American IPA
10311  10311.0        American IPA
10312  10312.0        American IPA
10313  10313.0        American IPA

[10314 rows x 2 columns]

In [72]:
submission1["Id"].astype("int")

0            0
1            1
2            2
3            3
4            4
         ...  
10309    10309
10310    10310
10311    10311
10312    10312
10313    10313
Name: Id, Length: 10314, dtype: int64

In [73]:
submission1.to_csv('submission1.csv', index=False)

In [74]:
submission1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10314 entries, 0 to 10313
Data columns (total 2 columns):
Id       10314 non-null float64
Style    10314 non-null object
dtypes: float64(1), object(1)
memory usage: 161.3+ KB


In [78]:
submission1["Id"] = submission1["Id"].astype("int32")

In [79]:
submission1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10314 entries, 0 to 10313
Data columns (total 2 columns):
Id       10314 non-null int32
Style    10314 non-null object
dtypes: int32(1), object(1)
memory usage: 121.0+ KB


In [80]:
submission1.to_csv('submission3.csv', index=False)